kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - go test ./...
- name: build
  image: golang
  commands:
  - go build
- name: docker  
  image: plugins/docker
  settings:
    registry: tg-tc:10443
    repo: tg-tc:10443/surfacemap
    tags: latest
    debug: false
    insecure: false
    when:
      branch: master
      status: success

